version: "3"
services: 
  vault:
    ports:
      - 8200:8200 # Api Address
      - 8201:8201 # Cluster Address
  app:
    volumes:
      - ../app:/app
      - app_node_modules:/app/node_modules
    command: sleep infinity
    ports:
    - 8080:8080
volumes:
  app_node_modules: {}
