version: "3"
services: 
  app:
    build:
      context: ../app

  vault:
    image: vault:1.1.3
    volumes: 
      - vault_log:/vault/logs
      - vault_file:/vault/file
volumes:
  vault_log: {}
  vault_file: {}
